declare const _default: {
    MATIC: {
        MATIC: string;
        btcGateway: string;
        renBTC: string;
        wETH: string;
        WBTC: string;
        wNative: string;
        USDC: string;
        Router: string;
        Curve_Ren: string;
        sushiRouter: string;
        gatewayRegistry: string;
        safeProxyFactory: string;
        multiSend: string;
        safeMasterCopy: string;
    };
    ARBITRUM: {
        renBTC: string;
        wETH: string;
        wNative: string;
        btcGateway: string;
        USDC: string;
        WBTC: string;
        Router: string;
        sushiRouter: string;
        Curve_Ren: string;
        gatewayRegistry: string;
        safeProxyFactory: string;
        multiSend: string;
        safeMasterCopy: string;
    };
    ETHEREUM: {
        ETH: string;
        renBTC: string;
        wETH: string;
        wNative: string;
        WBTC: string;
        ibBTC: string;
        USDC: string;
        Curve_SBTC: string;
        Curve_TriCryptoTwo: string;
        Curve_Ren: string;
        Router: string;
        sushiRouter: string;
        gatewayRegistry: string;
        btcGateway: string;
        safeProxyFactory: string;
        multiSend: string;
        safeMasterCopy: string;
    };
    AVALANCHE: {
        AVAX: string;
        renBTC: string;
        Curve_Ren: string;
        aTricrypto: string;
        WBTC: string;
        USDC: string;
        Curve_SBTC: string;
        Curve_TriCryptoTwo: string;
        Router: string;
        btcGateway: string;
    };
};
export default _default;
